"""Initial schema v2

Revision ID: cc37bc6a6e16
Revises: 
Create Date: 2026-01-24 00:13:17.214886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc37bc6a6e16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enforced_channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('owners',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('protected_groups',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index('idx_groups_enabled', 'protected_groups', ['enabled'], unique=False)
    op.create_index('idx_groups_owner', 'protected_groups', ['owner_id'], unique=False)
    op.create_table('group_channel_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['enforced_channels.channel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['protected_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'channel_id', name='uq_group_channel')
    )
    op.create_index('idx_links_channel', 'group_channel_links', ['channel_id'], unique=False)
    op.create_index('idx_links_group', 'group_channel_links', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_links_group', table_name='group_channel_links')
    op.drop_index('idx_links_channel', table_name='group_channel_links')
    op.drop_table('group_channel_links')
    op.drop_index('idx_groups_owner', table_name='protected_groups')
    op.drop_index('idx_groups_enabled', table_name='protected_groups')
    op.drop_table('protected_groups')
    op.drop_table('owners')
    op.drop_table('enforced_channels')
    # ### end Alembic commands ###
